export const POST_SUBMIT_CONFESSION  = 'POST_SUBMIT_CONFESSION';
export const GET_PENDING_CONFESSIONS = 'GET_PENDING_CONFESSIONS';
export const GET_APPROVED_CONFESSIONS = 'GET_APPROVED_CONFESSIONS';
export const GET_REJECTED_CONFESSIONS = 'GET_REJECTED_CONFESSIONS';

export const INCREMENT_ACTIVE_PAGE = 'INCREMENT_ACTIVE_PAGE';
export const DECREMENT_ACTIVE_PAGE = 'DECREMENT_ACTIVE_PAGE';

export const SELECT_PENDING_CONFESSION = 'SELECT_PENDING_CONFESSION';
export const DESELECT_PENDING_CONFESSION = 'DESELECT PENDING_CONFESSION';

export const POST_APPROVE_CONFESSIONS   = 'POST_APPROVE_CONFESSIONS';
export const POST_REJECT_CONFESSIONS    = 'POST_REJECT_CONFESSIONS';

export const SET_DISPLAY_IMAGES = 'SET_DISPLAY_IMAGES';
export const REMOVE_DISPLAY_IMAGES = 'REMOVE_DISPLAY_IMAGES';

