export const POST_SUBMIT_CONFESSION  = 'POST_SUBMIT_CONFESSION';
export const GET_PENDING_CONFESSIONS = 'GET_PENDING_CONFESSIONS';

export const INCREMENT_ACTIVE_PAGE = 'INCREMENT_ACTIVE_PAGE';
export const DECREMENT_ACTIVE_PAGE = 'DECREMENT_ACTIVE_PAGE';

export const SELECT_PENDING_CONFESSION = 'SELECT_PENDING_CONFESSION';
export const DESELECT_PENDING_CONFESSION = 'DESELECT PENDING_CONFESSION';